name: Release CI

on:
  push:
    tags: "v*" # push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-yarn
      - name: Set env
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo "RELEASE_NAME=${RELEASE_VERSION:1}" >> $GITHUB_ENV
      - name: Zip
        run: |
          cd packages

          # Remove Dynamic Subset Files
          find -wholename "**/web/*/*dynamic-subset*" -delete
          find -wholename "**/web/*/WEMIXPretendard*.css"  -delete

          # Zip
          (cd wemix-pretendard/dist && zip -rv - .) > WEMIXPretendard-${{ env.RELEASE_NAME }}.zip
          (cd wemix-pretendard-jp/dist && zip -rv - .) > WEMIXPretendardJP-${{ env.RELEASE_NAME }}.zip
      - uses: softprops/action-gh-release@v1 # actions/create-release, actions/upload-release-asset is deprecated
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            packages/WEMIXPretendard-${{ env.RELEASE_NAME }}.zip
            packages/WEMIXPretendardJP-${{ env.RELEASE_NAME }}.zip
